name: Test Coveralls

on:
    push:
        paths:
            - 'src/**'
            - 'tests/**'
        branches: [master]
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: npm install, npm test:lcov
              run: |
                  npm install
                  npm run test:lcov
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
